plugins {
    id("com.android.application")
        .version("7.4.2")
        .apply(false)
    id("com.android.library")
        .version("7.4.2")
        .apply(false)
    id("org.jetbrains.kotlin.android")
        .version("1.8.0")
        .apply(false)
    id("com.gradle.plugin-publish")
        .version("1.2.0")
        .apply(false)
    id("android.build.aspectj")
        .apply(false)
}