plugins {
    id("com.android.application")
        .version("7.4.2")
        .apply(false)
    id("com.android.library")
        .version("7.4.2")
        .apply(false)
    id("org.jetbrains.kotlin.android")
        .version("1.8.0")
        .apply(false)
    id("top.amake.aspectj")
        .apply(false)
    id("top.amake.legu")
        .apply(false)
}